application: jandjmaps
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js
  
- url: /img
  static_dir: img
  
- url: /chapters/.*
  script: jjmaps.py
  login: admin

- url: /.*
  script: jjmaps.py

